### ISSUE TITLE
 Main Menu Header

### ISSUE THREAD

**Issue by askingalot** [nss-day-cohort-41/tabloidcli-miss-piggy-s-devoted-disciples-rose#1]
As the application user, I would like to see a pleasant greeting when I start the application because I like pleasant greetings.

**Given** a user starts the program from the command line  
**When** the program starts  
**Then** a pleasant greeting should appear above the main menu

**Comment by Tlane77** [comment]
Add a Console.WriteLine A Pleasant Greeting to the Program.cs ( Above Main Menu)
